blank_issues_enabled: true

contact_links:
  - name: ðŸ’¬ GitHub Discussions
    url: https://github.com/orgs/krono-org/discussions
    about: Do you have a query or question about usage? Please do not open an issue; ask here instead.
